config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get :revisions, to: 'revisions#index'
  get :diff, to: 'diff#show'
  get :graph, to: 'graph#show'
  get 'job/:job', to: 'data#job'

  root 'revisions#index'
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  include Repository
  include Artifacts

  def index
    add_filtered_param!(:branch, git_remote_branches, 'remotes/origin/master')
    add_filtered_param!(:page, :int, 0)
    add_filtered_param!(:per_page, :int, 20)
    add_filtered_param!(:vmset, ['rsh', 'legacy', 'all'], 'rsh')
    add_filtered_param!(:filter, ['all', 'merges'], 'all')
    return if enforce_params!

    @branches = git_remote_branches

    hashes = []
    Filelock repo_conf[:lock] do
      git_repo.checkout(@branch)
      if @filter == 'merges'
        hashes = git_repo.log((@page+1) * (@per_page * 100))
                         .select{|c| c.message =~ /Merge pull request/}
      else
        hashes = git_repo.log(@per_page*(@page+1))
      end
      hashes = hashes[(@per_page*@page) .. (@per_page*(@page+1))]
    end

    @vmset_items = case @vmset
            when 'rsh'
              {artifact_job_names.keys.first => artifact_job_names.values.first}
            when 'all'
              Hash[artifact_job_names.reject{|n| n =~ /ginger/}]
            else
              artifact_job_names
            end

    @log = Hash[hashes.map do |c|
      jobs = gitlab_artifacts_info(c, @vmset_items.keys)
      [c, Hash[
          jobs.map do |n, v|
            [n, v['id']] if v && v.any?
          end.compact]]
    end]
  end
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/views/revisions/index.html.erb
<div class="row">
  <div class="col">
    <%= form_with(url: revisions_path, method: "get", local: true) do |form| %>
      <%= add_params(form, :per_page) %>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text" for="inputGroupSelect01">Per Page</label>
        </div>
      <%= select_tag(:per_page,
                     options_for_select([5,10,20,40,60,80,100],
                                        selected: @per_page),
                    onchange: ("this.form.submit()"),
                    class: "custom-select")%>
      </div>
    <% end %>
  </div>
  <div class="col">
    <%= form_with(url: revisions_path, method: "get", local: true) do |form| %>
      <%= add_params(form, :branch) %>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text" for="inputGroupSelect01">Branch</label>
        </div>
        <%= select_tag(:branch,
                       options_for_select(@branches.map{|b| [b.to_s.gsub("remotes/origin/",""), b]},
                                          selected: @branch),
                       onchange: ("this.form.submit()"),
                       class: "custom-select")%>
      </div>
    <% end %>
  </div>

  <div class="col">
    <nav aria-label="Page navigation">
      <ul class="pagination">
        <li class="page-item<%= ' disabled' if @page == 0 %>">
          <%= link_to '<span aria-hidden="true">&laquo;</span>'.html_safe,
            current_path.merge(page: @page-1), class: "page-link", 'aria-label': "Previous" %>
        </li>
        <li class="page-item active">
          <a class="page-link" href="#"><%= @page %><span class="sr-only">(current)</span></a>
        </li>
        <li class="page-item">
          <%= link_to '<span aria-hidden="true">&raquo;</span>'.html_safe,
            current_path.merge(page: @page+1), class: "page-link", 'aria-label': "Next" %>
        </li>
      </ul>
    </nav>
  </div>

  <div class="col">
    <%= form_with(url: revisions_path, method: "get", local: true) do |form| %>
      <%= add_params(form, :vmset) %>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text" for="inputGroupSelect01">vms</label>
        </div>
        <%= select_tag(:vmset,
                       options_for_select({'Ř' => 'rsh', all: 'all', legacy: 'legacy'},
                                          selected: @vmset),
                       onchange: ("this.form.submit()"), class: "custom-select")%>
      </div>
    <% end %>
  </div>

  <div class="col">
    <%= form_with(url: revisions_path, method: "get", local: true) do |form| %>
      <%= add_params(form, :filter) %>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text" for="inputGroupSelect01">filter</label>
        </div>
        <%= select_tag(:filter,
                       options_for_select({'all' => 'all', 'Merge requests' => 'merges'},
                                          selected: @filter),
                       onchange: ("this.form.submit()"), class: "custom-select")%>
      </div>
    <% end %>
  </div>

  <div class="col">
    <%= submit_tag 'compare', class: 'btn btn-primary', form: "jobs" %>
  </div>
</div>

<%= form_with(url: diff_path, method: "get", local: true, id: "jobs") do %>

<table class="table">
  <thead>
    <tr>
      <th colspan="2" scope="col">Commit</th>
      <% @vmset_items.size.times do |i| %>
        <th class="rotate" scope="col"><div><span><%= @vmset_items.values[i] %></span></div></th>
      <% end %>
    </tr>
  </thead>
  <% @log.each do |log, jobs| %>
    <tr>
      <th scope="row"><%= log.sha[0..6] %></th>
      <td><%= log.message.truncate(80) %> </td>
      <% @vmset_items.each do |n, name| %>
        <td>
          <% if jobs[n] %>
            <div class="form-check form-check-inline">
              <%= check_box 'jobs', jobs[n] %>
              <label class="form-check-label" for="inlineCheckbox2">
                <%= link_to '<span class="glyphicon glyphicon-download" aria-hidden="true"></span>'.html_safe, "job/#{jobs[n]}.csv", style: 'margin-left: 20px;', class: 'form-check-input' %>
              </label>
            </div>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<% end %>