config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get :revisions, to: 'revisions#index'
  get :diff, to: 'diff#show'
  get :graph, to: 'graph#show'
  get 'job/:job', to: 'data#job'

  root 'revisions#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeasuR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">measuR</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% {Compare: revisions_path, Graph: graph_path}.each do |name, link| %>
            <li class="nav-item<%= if current_page?(link) then ' active' else '' end %>">
              <a class="nav-link" href="<%= link %>"><%= name %></a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>